name: itckfa
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+21

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  image_cropper: ^3.0.0
  expandable: ^5.0.1
  getwidget: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5

  #Use to hide text and read more text
  readmore: ^2.0.1

  # use link widget
  url_launcher: ^6.0.12

  # handle SVGs for android, IOS, and web.
  #websafe_svg: ^1.1.4+2
  flutter_svg: ^1.1.5
  line_awesome_flutter: ^2.0.0
  settings_ui: ^2.0.2

  # which supports multiple comlumns with rows of varying sizes
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.17.0

  carousel_slider: ^4.1.1
  shared_preferences: ^2.0.15
  image_gallery_saver: ^2.0.3
  aba_payment: ^0.0.3
  flutter_easyloading: ^3.0.5
  flutter_dotenv: ^5.0.2
  sizer: ^2.0.15
  flutter_email_sender: ^5.2.0
  responsive_sizer: ^3.1.1
  google_maps_flutter: ^2.2.0
  awesome_dialog: ^3.0.2
  location_geocoder: ^1.0.5
  search_map_location: ^0.0.6
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.0.9
  pdf: ^3.8.3
  open_file: ^3.2.1
  path_provider: ^2.0.14
  file_picker: ^4.6.1
  custom_info_window: ^1.0.1
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  circular_menu: ^2.0.1
  animated_text_kit: ^4.2.2
  uuid: ^3.0.6
  anim_search_bar: ^2.0.2
  sqflite: ^2.0.2
  flutter_image_compress: ^1.1.3
  screenshot: ^2.1.0
  printing: ^5.9.3
  audioplayers: ^3.0.0
  tap_builder: ^0.4.0
  invoiceninja: ^0.0.9
  transparent_image: ^2.0.0
  animated_background: ^2.0.0
  video_player: ^2.5.1
  multi_image_picker: ^4.8.01
  cached_network_image: ^3.2.3
  number_pagination: ^0.0.3+2
  barcode_widget: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^4.0.1
  firebase_auth: ^4.7.1
  firebase_messaging: ^14.6.5
  pin_code_fields: ^7.0.0
  phone_number: ^0.12.0+1
  country_code_picker: ^2.0.2
  firebase_core: ^2.15.0
  pinput: ^2.2.12
  firebase_dynamic_links: ^5.3.4
  open_mail_app: ^0.4.5
  go_router: ^10.1.0
  shimmer: ^3.0.0
  liquid_progress_indicator_v2: ^0.5.0
  path_provider_android: ^2.2.0

  app_links: ^3.4.3
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.4
  image_picker_android: ^0.8.7+5
  get: ^4.6.5
  permission_handler: ^10.4.5
  uni_links: ^0.5.1
  onesignal_flutter: ^5.0.0
  flutter_inappwebview: ^5.8.0
  dio: ^4.0.6
  any_link_preview: ^3.0.0
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_wkwebview: ^3.9.4
  in_app_purchase: 3.1.11
  in_app_purchase_storekit: ^0.3.7
  http: ^0.13.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/25_commune/
    - assets/
    - assets/earth.gif
    - assets/icons/
    - assets/images/
    - assets/images/Partners/
    - assets/images/Membership/
    - assets/images/Letter En-Kh.svg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
