// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  String projectNumber = "390050660817";
  String webAPIKey = "AIzaSyAEHE_tC8re0HgCUv5G-csJO6uX4z1jYB8";
  String appID = "1:390050660817:android:de97801037ab42491f20f0";
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEHE_tC8re0HgCUv5G-csJO6uX4z1jYB8',
    appId: "1:390050660817:android:de97801037ab42491f20f0",
    messagingSenderId: '266399223712',
    projectId: 'kfa-crm-map',
    authDomain: 'kfa-crm-map.firebaseapp.com',
    storageBucket: 'kfa-crm-map.appspot.com',
    measurementId: 'G-HYMVYXE6HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHE_tC8re0HgCUv5G-csJO6uX4z1jYB8',
    appId: '1:390050660817:android:de97801037ab42491f20f0',
    messagingSenderId: '266399223712',
    projectId: 'kfa-crm-map',
    storageBucket: 'kfa-crm-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHE_tC8re0HgCUv5G-csJO6uX4z1jYB8',
    appId: '1:390050660817:android:de97801037ab42491f20f0',
    messagingSenderId: '266399223712',
    projectId: 'kfa-crm-map',
    storageBucket: 'kfa-crm-map.appspot.com',
    androidClientId:
        '266399223712-2td4r2gouru0d6shvvgruv6rnp928umi.apps.googleusercontent.com',
    iosBundleId: 'com.oneclickonedollars.itckfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEHE_tC8re0HgCUv5G-csJO6uX4z1jYB8',
    appId: '1:266399223712:ios:b1cb555fc6ae20f45edec5',
    messagingSenderId: '266399223712',
    projectId: 'kfa-crm-map',
    storageBucket: 'kfa-crm-map.appspot.com',
    androidClientId:
        '266399223712-2td4r2gouru0d6shvvgruv6rnp928umi.apps.googleusercontent.com',
    iosBundleId: 'no',
  );
}
